@auth_host = http://localhost:8080
@config_host = http://localhost:8080


@email = krasina_2003@mail.ru

################################################################################
### 1. регистрация
POST {{auth_host}}/auth/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "password123",
  "name": "Angelika"
}

################################################################################
### 2. логин
POST {{auth_host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "password123"
}

### ↓ после выполнения скопируйте токены из ответа: ###########################
#   "token": {                          <‑‑‑ access / refresh внутри
#       "access_token":  "...",
#       "refresh_token": "...",
#       "expires_at":   "..."
#   }
################################################################################
@access_token  = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZvcm1haWx2bGFkaXNAZ21haWwuY29tIiwiZXhwIjoxNzUwMDg1MDUxLCJ1c2VyX2lkIjoiYjFmZGQxMDgtYmQ5Yi00NzA1LThlMGUtOTE5OTQwZTJjOGVlIn0.nxkuE8PJaLX26kKmBNibqHGeNuCLn4VdmqZF9lGxt_w
@refresh_token = 1
################################################################################
### 3. 
GET {{auth_host}}/auth/me
Authorization: Bearer {{access_token}}

################################################################################
### 4. обновление токена
POST {{auth_host}}/auth/refresh
Content-Type: application/json

{
  "refresh_token": "{{refresh_token}}"
}


################################################################################
### 5. запрос на сброс пароля
POST {{auth_host}}/auth/forgot_password
Content-Type: application/json

{
  "email": "{{email}}"
}

### в письме/логе будет ссылка вида
# http://localhost:8080/auth/reset_password?token=XYZ
# скопируйте значение XYZ:

@reset_token = DneFmaBbM-y5cgjCD8FyKHQPKaUmEzbTMC1Nch-YQQE=

################################################################################
### 6. завершение сброса пароля
POST {{auth_host}}/auth/reset_password
Content-Type: application/json

{
  "reset_token": "{{reset_token}}",
  "new_password": "newpassword123"
}

################################################################################
### 7. логин новым паролем
POST {{auth_host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "newpassword123"
}

################################################################################
### 7. подтверждение e‑mail
POST {{auth_host}}/auth/verify_email
Content-Type: application/json

{
  "email": "{{email}}",
  "verification_code": "uAyBjQPm"
}

################################################################################
### 8. выход (logout)
POST {{auth_host}}/auth/logout
Authorization: Bearer {{access_token}}


################################################################################
### 9. удаление аккаунта (DELETE)
DELETE {{auth_host}}/auth/delete
Authorization: Bearer {{access_token}}

### 10. получить список компонентов
GET {{config_host}}/config/components

### 11.1 получить компоненты по категории
GET {{config_host}}/config/components?category=ssd

### 11.2 получить компоненты по категории и бренду
GET {{config_host}}/config/components?category=hdd&brand=Seagate

### 11.3 получить компоненты по категории и сценарию сборки 
GET {{config_host}}/config/components?category=motherboard&usecase=office

### 12. получить бренды по категории
GET {{config_host}}/config/brands?category=motherboard

################################################################################
### 13. поиск компонентов по названию
GET {{config_host}}/config/components?search=ryzen

################################################################################
### 14. создание конфигурации
@config_name = My First PC Build

POST {{config_host}}/config/newconfig
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "{{config_name}}",
  "components": [
    {
      "category": "CPU",
      "name": "AMD Ryzen 5 5600X"
    },
    {
      "category": "GPU",
      "name": "NVIDIA GeForce RTX 3060"
    }
  ]
}

### ↓ после выполнения скопируйте поле id конфигурации ########################
@config_id = 1

### 14.1. попытка создать конфигурацию с несовместимыми компонентами
@config_name1 = InvalidSocketBuild

POST {{config_host}}/config/newconfig
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "{{config_name}}",
  "components": [
    {
      "category": "cpu",
      "name": "AMD Ryzen 5 5600X"
    },
    {
      "category": "motherboard",
      "name": "ASUS PRIME B660-PLUS"
    }
  ]
}

### 14.2. обновление конфигурации
PUT {{config_host}}/config/newconfig/{{config_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Updated PC Build",
  "components": [
    {
      "category": "CPU",
      "name": "AMD Ryzen 7 7700X"
    },
    {
      "category": "GPU",
      "name": "AMD Radeon RX 6700 XT"
    }
  ]
}


### 14.3. удалить конфигурацию
DELETE {{config_host}}/config/newconfig/{{config_id}}
Authorization: Bearer {{access_token}}

################################################################################
### 15. получить конфигурации пользователя
GET {{config_host}}/config/userconf
Authorization: Bearer {{access_token}}


################################################################################
### 16. получить совместимые компоненты

### 1) Материнские платы, совместимые с CPU «AMD Ryzen 5 5600X»
POST {{config_host}}/config/compatible
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "category": "motherboard",
  "bases": [
    { "category": "cpu", "name": "AMD Ryzen 5 5600X" }
  ],
  "brand": "MSI"      
}

### 2) SSD, совместимые с материнской платой «MSI B550 Tomahawk»
POST {{config_host}}/config/compatible
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "category": "ssd",
  "bases": [
    { "category": "motherboard", "name": "MSI B550 Tomahawk" }
  ],
  "usecase": "gaming"
}

### 3) PSU, способные питать одновременно CPU и GPU
POST {{config_host}}/config/compatible
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "category": "psu",
  "bases": [
    { "category": "cpu", "name": "AMD Ryzen 5 5600X" },
    { "category": "gpu", "name": "NVIDIA GeForce RTX 3060" }
  ]
}

### 4) Cooler, способные охлаждать CPU и входить в CASE
POST  {{config_host}}/config/compatible
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "category": "cooler",
  "bases": [
    { "category":"cpu", "name":"AMD Ryzen 5 5600X" },
    { "category":"case", "name":"NZXT H510" }
  ]
}

### 5) Case
POST  {{config_host}}/config/compatible
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "category": "case",
  "bases": [
    { "category":"cpu", "name":"AMD Ryzen 5 5600X" },
    { "category":"ssd", "name":"Sabrent Rocket 4 Plus 2TB" }
  ]
}

################################################################################
### 17. получить список сценариев
GET {{config_host}}/config/usecases

################################################################################
### 18. получить готовые сборки по сценарию 
GET {{config_host}}/config/usecase/office



         
### 19. GET на агрегатор
GET http://localhost:8080/offers?componentId=1&sort=priceAsc
Authorization: Bearer {{access_token}}

### 20. Минимальная цена агрегатора
GET http://localhost:8080/offers/min?componentId=12

###################Не работает в REST-тестах
POST http://localhost:8080/offers/import
Content-Type: multipart/form-data

file=@./dns_pricelist.xlsx;type=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

### 21. Post на создание подписки
POST http://localhost:8080/subscriptions
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "componentId": "1000"
}

###Notifications GET на Redis
GET http://localhost:8080/notifications/count
Authorization: Bearer {{access_token}}

###Post на Redis
@notificationId = 77847fc5-9ba5-47b7-a7d6-067532edea19
POST http://localhost:8080/notifications/{{notificationId}}/read
Authorization: Bearer {{access_token}}

###Страница с уведомлениями
GET http://localhost:8080/notifications?
    page=1&
    pageSize=10
Authorization: Bearer {{access_token}}